version: "3.7"

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'eno_suity'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0' "
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db